### DISCUSSION TITLE
输入手机号点发送验证码的时候没反应

### DISCUSSION THREAD

**Discussion by pengxiangzhe** [luoling8192/telegram-search#222] [Q&A]
电脑小白折腾半天好不容易启动成功了，可为啥点半天发送验证码没反应，我在tg群里问了下大家，好像是配置文件代理没配置好，我用的clashsocks端口，测试tg连接代理没问题，但对于怎么在配置文件里写代理犯了难，我问了perplexity和chatGPT很多次，每次都不行，解决不了问题，不得已麻烦各位了，我已经研究了大半天了，有点小崩溃了哈哈，好难......

**Comment by luoling8192** [comment]
```yaml
proxy:
  ip: '127.0.0.1'
  port: 7890
```
